package com.entity;

// Generated 2016-4-12 23:28:16 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * CheckOut generated by hbm2java
 */
@Entity
@Table(name = "check_out", catalog = "aa")
@DynamicInsert(true)
@DynamicUpdate(true)
public class CheckOut implements java.io.Serializable {

	private Long checkOutId;
	private String checkOutTime;
	private String reason;
	private String createdByUser;
	private String updateByUser;
	private long studentId;
	private int buildingNo;

	public CheckOut() {
	}

	public CheckOut(String checkOutTime, String reason, String createdByUser,
			String updateByUser, long studentId, int buildingNo) {
		this.checkOutTime = checkOutTime;
		this.reason = reason;
		this.createdByUser = createdByUser;
		this.updateByUser = updateByUser;
		this.studentId = studentId;
		this.buildingNo = buildingNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "check_out_id", unique = true, nullable = true)
	public Long getCheckOutId() {
		return this.checkOutId;
	}

	public void setCheckOutId(Long checkOutId) {
		this.checkOutId = checkOutId;
	}

	@Column(name = "check_out_time", nullable = true, length = 54)
	public String getCheckOutTime() {
		return this.checkOutTime;
	}

	public void setCheckOutTime(String checkOutTime) {
		this.checkOutTime = checkOutTime;
	}

	@Column(name = "reason", nullable = true)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "created_by_user", nullable = true, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "update_by_user", nullable = true, length = 64)
	public String getUpdateByUser() {
		return this.updateByUser;
	}

	public void setUpdateByUser(String updateByUser) {
		this.updateByUser = updateByUser;
	}

	@Column(name = "student_id", nullable = true)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	@Column(name = "building_no", nullable = true)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

}
