package com.entity;

// Generated 2016-4-12 23:28:16 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * CheckIn generated by hbm2java
 */
@Entity
@Table(name = "check_in", catalog = "aa")
@DynamicInsert(true)
@DynamicUpdate(true)
public class CheckIn implements java.io.Serializable {

	private Long checkInId;
	private long studentId;
	private long romeId;
	private String checkInTime;
	private String createdByUser;
	private String updatedByUser;
	private String reason;
	private int buildingNo;

	public CheckIn() {
	}

	public CheckIn(long studentId, long romeId, String checkInTime,
			String createdByUser, String updatedByUser, String reason,
			int buildingNo) {
		this.studentId = studentId;
		this.romeId = romeId;
		this.checkInTime = checkInTime;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
		this.reason = reason;
		this.buildingNo = buildingNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "check_in_id", unique = true, nullable = true)
	public Long getCheckInId() {
		return this.checkInId;
	}

	public void setCheckInId(Long checkInId) {
		this.checkInId = checkInId;
	}

	@Column(name = "student_id", nullable = true)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	@Column(name = "rome_id", nullable = true)
	public long getRomeId() {
		return this.romeId;
	}

	public void setRomeId(long romeId) {
		this.romeId = romeId;
	}

	@Column(name = "check_in_time", nullable = true, length = 64)
	public String getCheckInTime() {
		return this.checkInTime;
	}

	public void setCheckInTime(String checkInTime) {
		this.checkInTime = checkInTime;
	}

	@Column(name = "created_by_user", nullable = true, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = true, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

	@Column(name = "reason", nullable = true)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "building_no", nullable = true)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

}
