package com.entity;

// Generated 2016-3-27 13:53:12 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Houseparent generated by hbm2java
 */
@Entity
@Table(name = "houseparent", catalog = "dormitory")
@DynamicInsert(true)
@DynamicUpdate(true)
public class Houseparent implements java.io.Serializable {

	private Long houseparentId;
	private String houseparentName;
	private byte sex;
	private int houseparentNo;
	private int buildingNo;
	private String idCard;
	private String telephone;
	private String createdByUser;
	private String updatedByUser;

	public Houseparent() {
	}

	public Houseparent(String houseparentName, byte sex, int houseparentNo,
			int buildingNo, String idCard, String telephone,
			String createdByUser, String updatedByUser) {
		this.houseparentName = houseparentName;
		this.sex = sex;
		this.houseparentNo = houseparentNo;
		this.buildingNo = buildingNo;
		this.idCard = idCard;
		this.telephone = telephone;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "houseparent_id", unique = true, nullable = true)
	public Long getHouseparentId() {
		return this.houseparentId;
	}

	public void setHouseparentId(Long houseparentId) {
		this.houseparentId = houseparentId;
	}

	@Column(name = "houseparent_name", nullable = true, length = 64)
	public String getHouseparentName() {
		return this.houseparentName;
	}

	public void setHouseparentName(String houseparentName) {
		this.houseparentName = houseparentName;
	}

	@Column(name = "sex", nullable = true)
	public byte getSex() {
		return this.sex;
	}

	public void setSex(byte sex) {
		this.sex = sex;
	}

	@Column(name = "houseparent_no", nullable = true)
	public int getHouseparentNo() {
		return this.houseparentNo;
	}

	public void setHouseparentNo(int houseparentNo) {
		this.houseparentNo = houseparentNo;
	}

	@Column(name = "building_no", nullable = true)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

	@Column(name = "id_card", nullable = true, length = 32)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "telephone", nullable = true, length = 32)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "created_by_user", nullable = true, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = true, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
