package com.entity;

// Generated 2016-4-15 16:30:02 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Postcard generated by hbm2java
 */
@Entity
@Table(name = "postcard", catalog = "dormitory")
@DynamicInsert(true)
@DynamicUpdate(true)
public class Postcard implements java.io.Serializable {

	private long postcardId;
	private Date time;
	private String sender;
	private String studentName;
	private int studentNo;
	private int buildingNo;
	private byte isRead;
	private String createdByUser;
	private String updatedByUser;

	public Postcard() {
	}

	public Postcard(long postcardId, Date time, String sender,
			String studentName, int studentNo, int buildingNo, byte isRead,
			String createdByUser, String updatedByUser) {
		this.postcardId = postcardId;
		this.time = time;
		this.sender = sender;
		this.studentName = studentName;
		this.studentNo = studentNo;
		this.buildingNo = buildingNo;
		this.isRead = isRead;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@Column(name = "postcard_id", unique = true, nullable = false)
	public long getPostcardId() {
		return this.postcardId;
	}

	public void setPostcardId(long postcardId) {
		this.postcardId = postcardId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "sender", nullable = false, length = 64)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "student_name", nullable = false, length = 64)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "student_no", nullable = false)
	public int getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(int studentNo) {
		this.studentNo = studentNo;
	}

	@Column(name = "building_no", nullable = false)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

	@Column(name = "is_read", nullable = false)
	public byte getIsRead() {
		return this.isRead;
	}

	public void setIsRead(byte isRead) {
		this.isRead = isRead;
	}

	@Column(name = "created_by_user", nullable = false, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = false, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
