package com.entity;

// Generated 2016-3-16 16:33:36 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Qq generated by hbm2java
 */
@Entity
@Table(name = "qq", catalog = "dormitory")
public class Qq implements java.io.Serializable {

	private int id;

	public Qq() {
	}

	public Qq(int id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
