package com.entity;

// Generated 2016-3-21 15:12:52 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RoleItem generated by hbm2java
 */
@Entity
@Table(name = "role_item", catalog = "aa")
public class RoleItem implements java.io.Serializable {

	private Long roleItemId;
	private int roleType;
	private long sysMenuItemId;
	private String createdByUser;
	private String updatedByUser;

	public RoleItem() {
	}

	public RoleItem(int roleType, long sysMenuItemId, String createdByUser,
			String updatedByUser) {
		this.roleType = roleType;
		this.sysMenuItemId = sysMenuItemId;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_item_id", unique = true, nullable = false)
	public Long getRoleItemId() {
		return this.roleItemId;
	}

	public void setRoleItemId(Long roleItemId) {
		this.roleItemId = roleItemId;
	}

	@Column(name = "role_type", nullable = false)
	public int getRoleType() {
		return this.roleType;
	}

	public void setRoleType(int roleType) {
		this.roleType = roleType;
	}

	@Column(name = "sys_menu_item_id", nullable = false)
	public long getSysMenuItemId() {
		return this.sysMenuItemId;
	}

	public void setSysMenuItemId(long sysMenuItemId) {
		this.sysMenuItemId = sysMenuItemId;
	}

	@Column(name = "created_by_user", nullable = false, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = false, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
