package com.entity;

// Generated 2016-3-22 17:34:00 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SbRoom generated by hbm2java
 */
@Entity
@Table(name = "sb_room", catalog = "aa")
public class SbRoom implements java.io.Serializable {

	private Long sbRoomId;
	private int roomNo;
	private int buildingNo;
	private BigDecimal area;
	private int bedNum;
	private int bedLeft;
	private String createdByUser;
	private String updatedByUser;

	public SbRoom() {
	}

	public SbRoom(int roomNo, int buildingNo, BigDecimal area, int bedNum,
			int bedLeft, String createdByUser, String updatedByUser) {
		this.roomNo = roomNo;
		this.buildingNo = buildingNo;
		this.area = area;
		this.bedNum = bedNum;
		this.bedLeft = bedLeft;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sb_room_Id", unique = true, nullable = false)
	public Long getSbRoomId() {
		return this.sbRoomId;
	}

	public void setSbRoomId(Long sbRoomId) {
		this.sbRoomId = sbRoomId;
	}

	@Column(name = "room_no", nullable = false)
	public int getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(int roomNo) {
		this.roomNo = roomNo;
	}

	@Column(name = "building_no", nullable = false)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

	@Column(name = "area", nullable = false, precision = 11)
	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	@Column(name = "bed_num", nullable = false)
	public int getBedNum() {
		return this.bedNum;
	}

	public void setBedNum(int bedNum) {
		this.bedNum = bedNum;
	}

	@Column(name = "bed_left", nullable = false)
	public int getBedLeft() {
		return this.bedLeft;
	}

	public void setBedLeft(int bedLeft) {
		this.bedLeft = bedLeft;
	}

	@Column(name = "created_by_user", nullable = false, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = false, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
