package com.entity;

// Generated 2016-3-23 17:31:53 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "aa")
@DynamicInsert(true)
@DynamicUpdate(true)
public class Student implements java.io.Serializable {

	private Long studentId;
	private String studentName;
	private long studentNo;
	private int buildingNo;
	private int roomNo;
	private String idCard;
	private String telephone;
	private byte sex;
	private String major;
	private String grade;
	private String studentClass;
	private byte isGraduated;
	private String teacher;
	private String createdByUser;
	private String updatedByUser;

	public Student() {
	}

	public Student(String studentName, long studentNo, int buildingNo,
			int roomNo, String idCard, String telephone, byte sex,
			String major, String grade, String studentClass, byte isGraduated,
			String teacher, String createdByUser, String updatedByUser) {
		this.studentName = studentName;
		this.studentNo = studentNo;
		this.buildingNo = buildingNo;
		this.roomNo = roomNo;
		this.idCard = idCard;
		this.telephone = telephone;
		this.sex = sex;
		this.major = major;
		this.grade = grade;
		this.studentClass = studentClass;
		this.isGraduated = isGraduated;
		this.teacher = teacher;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_id", unique = true, nullable = true)
	public Long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	@Column(name = "student_name", nullable = true, length = 32)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "student_no", nullable = true)
	public long getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(long studentNo) {
		this.studentNo = studentNo;
	}

	@Column(name = "building_no", nullable = true)
	public int getBuildingNo() {
		return this.buildingNo;
	}

	public void setBuildingNo(int buildingNo) {
		this.buildingNo = buildingNo;
	}

	@Column(name = "room_no", nullable = true)
	public int getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(int roomNo) {
		this.roomNo = roomNo;
	}

	@Column(name = "id_card", nullable = true, length = 32)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "telephone", nullable = true, length = 32)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "sex", nullable = true)
	public byte getSex() {
		return this.sex;
	}

	public void setSex(byte sex) {
		this.sex = sex;
	}

	@Column(name = "major", nullable = true, length = 32)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "grade", nullable = true, length = 32)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "student_class", nullable = true, length = 32)
	public String getStudentClass() {
		return this.studentClass;
	}

	public void setStudentClass(String studentClass) {
		this.studentClass = studentClass;
	}

	@Column(name = "is_graduated", nullable = true)
	public byte getIsGraduated() {
		return this.isGraduated;
	}

	public void setIsGraduated(byte isGraduated) {
		this.isGraduated = isGraduated;
	}

	@Column(name = "teacher", nullable = true, length = 32)
	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	@Column(name = "created_by_user", nullable = true, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = true, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
