package com.entity;

// Generated 2016-3-23 17:31:53 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * SysMenuGroup generated by hbm2java
 */
@Entity
@Table(name = "sys_menu_group", catalog = "aa")
@DynamicInsert(true)
@DynamicUpdate(true)
public class SysMenuGroup implements java.io.Serializable {

	private Long sysMenuGroupId;
	private String groupDesc;
	private String createdByUser;
	private String updatedByUser;

	public SysMenuGroup() {
	}

	public SysMenuGroup(String groupDesc, String createdByUser,
			String updatedByUser) {
		this.groupDesc = groupDesc;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sys_menu_group_Id", unique = true, nullable = true)
	public Long getSysMenuGroupId() {
		return this.sysMenuGroupId;
	}

	public void setSysMenuGroupId(Long sysMenuGroupId) {
		this.sysMenuGroupId = sysMenuGroupId;
	}

	@Column(name = "group_desc", nullable = true, length = 64)
	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	@Column(name = "created_by_user", nullable = true, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = true, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
