package com.entity;

// Generated 2016-3-21 15:12:52 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysMenuItem generated by hbm2java
 */
@Entity
@Table(name = "sys_menu_item", catalog = "aa")
public class SysMenuItem implements java.io.Serializable {

	private Long sysMenuItemId;
	private String menuTitle;
	private long sysMenuGroupId;
	private String url;
	private String createdByUser;
	private String updatedByUser;

	public SysMenuItem() {
	}

	public SysMenuItem(String menuTitle, long sysMenuGroupId, String url,
			String createdByUser, String updatedByUser) {
		this.menuTitle = menuTitle;
		this.sysMenuGroupId = sysMenuGroupId;
		this.url = url;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sys_menu_item_id", unique = true, nullable = false)
	public Long getSysMenuItemId() {
		return this.sysMenuItemId;
	}

	public void setSysMenuItemId(Long sysMenuItemId) {
		this.sysMenuItemId = sysMenuItemId;
	}

	@Column(name = "menu_title", nullable = false, length = 64)
	public String getMenuTitle() {
		return this.menuTitle;
	}

	public void setMenuTitle(String menuTitle) {
		this.menuTitle = menuTitle;
	}

	@Column(name = "sys_menu_group_id", nullable = false)
	public long getSysMenuGroupId() {
		return this.sysMenuGroupId;
	}

	public void setSysMenuGroupId(long sysMenuGroupId) {
		this.sysMenuGroupId = sysMenuGroupId;
	}

	@Column(name = "url", nullable = false, length = 64)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "created_by_user", nullable = false, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = false, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
