package com.entity;

// Generated 2016-3-21 15:12:52 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysMenuGroup generated by hbm2java
 */
@Entity
@Table(name = "sys_menu_group", catalog = "aa")
public class SysMenuGroup implements java.io.Serializable {

	private long sysMenuGroupId;
	private String groupDesc;
	private String createdByUser;
	private String updatedByUser;

	public SysMenuGroup() {
	}

	public SysMenuGroup(long sysMenuGroupId, String groupDesc,
			String createdByUser, String updatedByUser) {
		this.sysMenuGroupId = sysMenuGroupId;
		this.groupDesc = groupDesc;
		this.createdByUser = createdByUser;
		this.updatedByUser = updatedByUser;
	}

	@Id
	@Column(name = "sys_menu_group_Id", unique = true, nullable = false)
	public long getSysMenuGroupId() {
		return this.sysMenuGroupId;
	}

	public void setSysMenuGroupId(long sysMenuGroupId) {
		this.sysMenuGroupId = sysMenuGroupId;
	}

	@Column(name = "group_desc", nullable = false, length = 64)
	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	@Column(name = "created_by_user", nullable = false, length = 64)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "updated_by_user", nullable = false, length = 64)
	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
